---
# GitHub Actions Workflow CI/CD
#

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - run: echo "test stage"

  build:
    name: build
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout our code
        uses: actions/checkout@v2
      - run: |
          ls
          echo "build stage"

  deploy:
    name: deploy
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      -  run: echo "deploy stage"
